### ISSUE TITLE
Targetting Bindings section links to the incorrect page

### ISSUE THREAD

**Issue by exts** [opulencephp/docs#14]
**What:**

On this page https://www.opulencephp.com/docs/1.1/bootstrappers#targeted-bindings it should be linking the 'targeted bindings link' to: https://www.opulencephp.com/docs/1.0/ioc-container#targeting

**Instead:**
'targeted bindings' is linking to: https://www.opulencephp.com/docs/1.1/dependency-injection#targeted-bindings which gets redirected to the installation page.

**Comment by davidbyoung** [comment]
Fixed.  Thanks for finding this!
