### ISSUE TITLE
Fix bcrypt hashing intro

### ISSUE THREAD

**Issue by timoh6** [opulencephp/docs#2]
The paragraph about bcrypt hashing could use slight tuning, especially clause ". Every time the cost goes up by one, the hasher takes 10 times longer to hash" is wrong (the time doubles).

Just out of my hat, something along the lines:

> bcrypt is a popular password hashing function that accepts a configurable cost parameter, which adjust the CPU cost to hash a password. This slows down attacks against compromised data. Increasing the cost parameter by one, the hashing operation takes twice longer. You can adjust this value to make it future-proof. Let's take a look at how to use it:

**Comment by timoh6** [comment]
I'd still consider updating a few things regarding the bcrypt intro:
- To separate bcrypt (a password hashing function) from cryptographic hashing functions, like SHA-256, I'd include word "password": "bcrypt is a popular password hashing function". As password hashing functions has different use cases than cryptographic hash functions, I think it would be wise to make a clear distinction.
- Clause "that has built-in protection methods against timing attacks" is practically irrelevant, as timing attacks are not a concern here. I believe it would make the paragraph cleaner if this info was removed (to not to confuse readers).
- Clause "This slows down rainbow table attacks against compromised data" (which refers to the CPU cost) is not true as it is the salting that defeats rainbow tables. The CPU cost slows down (or makes more expensive) adversary's brute force attack (where she evaluates candidate passwords which hashes to the same value). If the "rainbow table" phrase was removed, the sentence looks correct to me.

**Comment by davidbyoung** [comment]
Agreed, and fixed.

**Comment by timoh6** [comment]
Looks good to me.
