### ISSUE TITLE
The dependency resolvers section on routing links to an invalid/missing/removed link

### ISSUE THREAD

**Issue by exts** [opulencephp/docs#8]
[This page](https://www.opulencephp.com/docs/1.0/routing#dependency-resolvers) there's a dependency injection container link which gets redirected to the installing page which seems incorrect/wrong. Not sure where the original link is supposed to point to though.

**Comment by davidbyoung** [comment]
Thanks for reporting this.  It goes to the [IoC container docs](https://www.opulencephp.com/docs/1.0/ioc-container).
